SELECT f.*,
 ROUND((s.Mate_Colegio+s.Lenguaje_Colegio)/(s.Personas_Colegio*2),2) AS Promedio_PSU_Colegio, s.Personas_Colegio AS Total_Alumnos_Colegio

FROM

(
SELECT 
    RIGHT(e.NUMERO_DOCUMENTO, 9) AS Cod_Persona,
    e.AÑO_PROCESO AS Año_Proceso, 
    SWITCH(CODIGO = '11026', 'CA', CODIGO = '11027', 'IICG', CODIGO = '11042', 'IC') AS Tipo_Alumno, 
    SWITCH(ESTADO_DE_POSTULACION = '24', 'Convocado', ESTADO_DE_POSTULACION = '25', 'Lista Espera') AS Estado_Postulacion,
    PREFERENCIA AS Preferencia_Carrera, MATEMATICA AS Ptje_PSU_Matematica,
    e.PTJE_RANKING AS Ptje_Ranking,
    e.LOCAL_EDUCACIONAL AS Local_Educacional,
    e.UNIDAD_EDUCATIVA AS Unidad_Educativa,
    SWITCH(e.GRUPO_DEPENDENCIA = '1', 'Particular Pagado', 
        e.GRUPO_DEPENDENCIA = '2', 'Particular Subvencionado', 
        e.GRUPO_DEPENDENCIA = '3', 'Municipal') AS Grupo_Dependencia,
    a.CODIGO_COMUNA AS Colegio_Cod_Comuna,
    e.COD_COMUNA AS Domicilio_Cod_Comuna,
    SWITCH (POND_AÑO_ACAD = '1', 'Actual', POND_AÑO_ACAD = '2', 'Anterior') AS PSU_Utilizada,
    b.INGRESO_BRUTO_FAMILIAR AS Ing_Bruto_Familiar,
    'PSU' AS Tipo_Ingreso

FROM 
    ((Archivo_E as e
    LEFT JOIN 
        Archivo_B AS b
        ON e.NUMERO_DOCUMENTO = b.NUMERO_DOCUMENTO)
 LEFT JOIN 
        Archivo_A AS a
        ON e.LOCAL_EDUCACIONAL = a.LOCAL_EDUCATIVA AND e.UNIDAD_EDUCATIVA = a.UNIDAD_EDUCATIVA )
   
WHERE
    CODIGO IN ('11026', '11027', '11042')

UNION ALL

SELECT 
    RIGHT(e.NUMERO_DOCUMENTO, 9) AS Cod_Persona,
    e.AÑO_PROCESO AS Año_Proceso, 
    SWITCH(CODIGO = '11026', 'CA', CODIGO = '11027', 'IICG', CODIGO = '11042', 'IC') AS Tipo_Alumno, 
    SWITCH(ESTADO_DE_POSTULACION = '24', 'Convocado', ESTADO_DE_POSTULACION = '25', 'Lista Espera') AS Estado_Postulacion,
    PREFERENCIA AS Preferencia_Carrera, MATEMATICA AS Ptje_PSU_Matematica,
    e.PTJE_RANKING AS Ptje_Ranking,
    e.LOCAL_EDUCACIONAL AS Local_Educacional,
    e.UNIDAD_EDUCATIVA AS Unidad_Educativa,
    SWITCH(e.GRUPO_DEPENDENCIA = '1', 'Particular Pagado', 
        e.GRUPO_DEPENDENCIA = '2', 'Particular Subvencionado', 
        e.GRUPO_DEPENDENCIA = '3', 'Municipal') AS Grupo_Dependencia,
    a.CODIGO_COMUNA AS Colegio_Cod_Comuna,
    e.COD_COMUNA AS Domicilio_Cod_Comuna,
    SWITCH (POND_AÑO_ACAD = '1', 'Actual', POND_AÑO_ACAD = '2', 'Anterior') AS PSU_Utilizada,
    b.INGRESO_BRUTO_FAMILIAR AS Ing_Bruto_Familiar,
    'BEA 5% SUPERIOR' AS Tipo_Ingreso

FROM 
    ((Archivo_E_BEA as e
    LEFT JOIN 
        Archivo_B AS b
        ON e.NUMERO_DOCUMENTO = b.NUMERO_DOCUMENTO)
 LEFT JOIN 
        Archivo_A AS a
        ON e.LOCAL_EDUCACIONAL = a.LOCAL_EDUCATIVA AND e.UNIDAD_EDUCATIVA = a.UNIDAD_EDUCATIVA )
   
WHERE
    CODIGO IN ('11026', '11027', '11042')

UNION ALL

SELECT 
    RIGHT(e.NUMERO_DOCUMENTO, 9) AS Cod_Persona,
    e.AÑO_PROCESO AS Año_Proceso, 
    'LIBRE' AS Tipo_Alumno, 
    SWITCH(ESTADO_DE_POSTULACION = '24', 'Convocado', ESTADO_DE_POSTULACION = '25', 'Lista Espera') AS Estado_Postulacion,
    PREFERENCIA AS Preferencia_Carrera, MATEMATICA AS Ptje_PSU_Matematica,
    e.PTJE_RANKING AS Ptje_Ranking,
    e.LOCAL_EDUCACIONAL AS Local_Educacional,
    e.UNIDAD_EDUCATIVA AS Unidad_Educativa,
    SWITCH(e.GRUPO_DEPENDENCIA = '1', 'Particular Pagado', 
        e.GRUPO_DEPENDENCIA = '2', 'Particular Subvencionado', 
        e.GRUPO_DEPENDENCIA = '3', 'Municipal') AS Grupo_Dependencia,
    a.CODIGO_COMUNA AS Colegio_Cod_Comuna,
    e.COD_COMUNA AS Domicilio_Cod_Comuna,
    SWITCH (POND_AÑO_ACAD = '1', 'Actual', POND_AÑO_ACAD = '2', 'Anterior') AS PSU_Utilizada,
    b.INGRESO_BRUTO_FAMILIAR AS Ing_Bruto_Familiar,
    'BACHILLERATO' AS Tipo_Ingreso

FROM 
    ((Archivo_E_BEA as e
    LEFT JOIN 
        Archivo_B AS b
        ON e.NUMERO_DOCUMENTO = b.NUMERO_DOCUMENTO)
 LEFT JOIN 
        Archivo_A AS a
        ON e.LOCAL_EDUCACIONAL = a.LOCAL_EDUCATIVA AND e.UNIDAD_EDUCATIVA = a.UNIDAD_EDUCATIVA )

WHERE 
(((e.NUMERO_DOCUMENTO)="17421297K" Or (e.NUMERO_DOCUMENTO)="180587926" Or (e.NUMERO_DOCUMENTO)="186744519" Or (e.NUMERO_DOCUMENTO)="190395065" Or (e.NUMERO_DOCUMENTO)="190771245" Or (e.NUMERO_DOCUMENTO)="19080030K" Or (e.NUMERO_DOCUMENTO)="190813959" Or (e.NUMERO_DOCUMENTO)="191865294" Or (e.NUMERO_DOCUMENTO)="192092795" Or (e.NUMERO_DOCUMENTO)="192465656" Or (e.NUMERO_DOCUMENTO)="192466423" Or (e.NUMERO_DOCUMENTO)="193078923" Or (e.NUMERO_DOCUMENTO)="193177166" Or (e.NUMERO_DOCUMENTO)="193223729" Or (e.NUMERO_DOCUMENTO)="193335918" Or (e.NUMERO_DOCUMENTO)="193382215" Or (e.NUMERO_DOCUMENTO)="193754260" Or (e.NUMERO_DOCUMENTO)="193762298" Or (e.NUMERO_DOCUMENTO)="193762956" Or (e.NUMERO_DOCUMENTO)="193852882" Or (e.NUMERO_DOCUMENTO)="194104936" Or (e.NUMERO_DOCUMENTO)="194384807" Or (e.NUMERO_DOCUMENTO)="194980892" Or (e.NUMERO_DOCUMENTO)="195142394" Or (e.NUMERO_DOCUMENTO)="195239134" Or (e.NUMERO_DOCUMENTO)="195436347" Or (e.NUMERO_DOCUMENTO)="196310827" Or (e.NUMERO_DOCUMENTO)="196665153" Or (e.NUMERO_DOCUMENTO)="196688420" Or (e.NUMERO_DOCUMENTO)="22670003K" Or (e.NUMERO_DOCUMENTO)="177402192" Or (e.NUMERO_DOCUMENTO)="189334664" Or (e.NUMERO_DOCUMENTO)="190770478" Or (e.NUMERO_DOCUMENTO)="19216799K" Or (e.NUMERO_DOCUMENTO)="192769620" Or (e.NUMERO_DOCUMENTO)="192935601" Or (e.NUMERO_DOCUMENTO)="194270178" Or (e.NUMERO_DOCUMENTO)="194835000" Or (e.NUMERO_DOCUMENTO)="195146616" Or (e.NUMERO_DOCUMENTO)="196352112" Or (e.NUMERO_DOCUMENTO)="197456523" Or (e.NUMERO_DOCUMENTO)="197737867" Or (e.NUMERO_DOCUMENTO)="198021687" Or (e.NUMERO_DOCUMENTO)="198601543" Or (e.NUMERO_DOCUMENTO)="198805181" Or (e.NUMERO_DOCUMENTO)="199537105"))
AND CODIGO IN('11078')
) AS f

LEFT JOIN (SELECT ae.LOCAL_EDUCACIONAL, 
 SWITCH(ae.GRUPO_DEPENDENCIA = '1', 'Particular Pagado', 
        ae.GRUPO_DEPENDENCIA = '2', 'Particular Subvencionado',
        ae.GRUPO_DEPENDENCIA = '3', 'Municipal') AS GRUPO_DEPENDENCIA,
             ae.GRUPO_DEPENDENCIA, 
             ae.UNIDAD_EDUCATIVA,
            SUM(ae.MATEMATICA) AS Mate_Colegio,
            SUM(LENGUAJE_Y_COMUNICACION) AS Lenguaje_Colegio,
             COUNT(ae.NUMERO_DOCUMENTO) AS Personas_Colegio
 
FROM Archivo_E as ae

GROUP BY  ae.LOCAL_EDUCACIONAL, ae.GRUPO_DEPENDENCIA, ae.UNIDAD_EDUCATIVA
)  AS s 
ON (f.Grupo_Dependencia=s.Grupo_Dependencia) AND (f.Unidad_Educativa=s.UNIDAD_EDUCATIVA) AND (f.Local_Educacional=s.LOCAL_EDUCACIONAL)